# Generated by Django 2.0.4 on 2018-04-28 13:03

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('program', wagtail.core.fields.StreamField((('day', wagtail.core.blocks.StructBlock((('date', wagtail.core.blocks.DateBlock(required=True)), ('program', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('timeslot', wagtail.core.blocks.CharBlock(required=True)), ('activity', wagtail.core.blocks.TextBlock(required=True)), ('notes', wagtail.core.blocks.TextBlock(required=False))))))))),))),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
